spring:
    profiles:
        active: windows
minium:
  developer:
    webdrivers:
      - name: chrome
        displayName: Chrome
        iconClass: icon-chrome
        desiredCapabilities:
          browserName: chrome
        chromeOptions:
          loggingPrefs:
            performance: INFO
      - name: firefox
        displayName: Firefox
        iconClass: icon-firefox
        desiredCapabilities:
          browserName: firefox
      - name: ie
        displayName: Internet Explorer
        iconClass: icon-ie
        desiredCapabilities:
          browserName: internet explorer
