# Web Drivers   
minium:
  webdriver:
    desiredCapabilities:
      browserName: chrome
    chromeOptions:
      loggingPrefs:
        performance: INFO
      args:
        - headless
        - no-sandbox
        - disable-gpu
        - window-size=1200,600
        - disable-local-storage
        - disk-cache-size=1
        - media-cache-size=1
        - disk-cache-dir=null
        - media-cache-dir=null
        - whitelisted-ips
    window:
      maximized: true

# Configuration that can be injected in your tests
  config:
    baseURL: https://minium.vilt.io/
    threshold: 3 # in seconds
    searches:
      Minium Github:
        - https://github.com/viltgroup/minium
      Selenium:
        - https://www.seleniumhq.org/