Vagrant.configure("2") do |config|

    config.vm.define "minium-developer" do |a|
        a.vm.provider "docker" do |d|
            d.image = "virtus:5000/minium-developer"
            d.name = "minium-developer"
            d.ports = ["8089:8089"]
            d.volumes = ["#{Dir.pwd}/bundle:/opt/minium-tools"]
        end
    end

end
